Repository hackerspace-ntnu/prosjekt-spill, pull requests merged in 2024-10, with the labels that each got.

#8 doc: add commit conventions manual
  docs/manuals/commit_conventions.md
Labels: documentation

#7 Create a general character ability system
  LICENSE.md
  README.md
  assets/models/soldier/Gun.glb
  assets/models/soldier/Gun.glb.import
  assets/textures/pngimg.com - bullet_hole_PNG6062.png
  assets/textures/pngimg.com - bullet_hole_PNG6062.png.import
  pexels-photo-413195.jpeg
  pexels-photo-413195.jpeg.import
  prefabs/abilities/soldier/Bullet.tscn
  prefabs/abilities/soldier/BulletHole.tscn
  prefabs/abilities/soldier/SoldierPrimary.tscn
  prefabs/player/PlayerUI.tscn
  prefabs/player/soldier/soldier.tscn
  project.godot
  prosjekt-spill-hs.csproj
  prosjekt-spill-hs.sln
  resources/classes/soldier/.gitkeep
  resources/classes/soldier/soldierPrimary.tres
  resources/classes/soldier/soldierSecondary.tres
  resources/classes/soldier/soldierUltimate.tres
  resources/classes/soldier/soldierUtilOne.tres
  resources/classes/soldier/soldierUtilTwo.tres
  scenes/MainScene.tscn
  scripts/classes/soldier/abilities/Bullet.cs
  scripts/classes/soldier/abilities/BulletHole.cs
  scripts/classes/soldier/abilities/SoldierPrimary.cs
  scripts/player/Ability.cs
  scripts/player/AbilityHandler.cs
  scripts/player/BaseCharacter.cs
Labels: enhancement

#11 Create ability system
  prefabs/player/soldier/soldier.tscn
  prefabs/proceduralMap/ProceduralMapGen.cs
  prefabs/proceduralMap/proceduralMapGen.tscn
  resources/classes/soldier/mage_primary.tres
  scripts/classes/soldier/abilities/SoldierPrimary.cs
  scripts/player/Ability.cs
  scripts/player/AbilityHandler.cs
  scripts/player/BaseCharacter.cs
Labels: enhancement, feature

#15 Feature/item template
  addons/.gitkeep
  prefabs/Items/ExampleItem.tscn
  project.godot
  resources/Items/exampleItem.tres
  scenes/MainScene.tscn
  scripts/Items/Item.cs
  scripts/Items/ItemSpawner.cs
Labels: feature
